# See https://github.com/docker/metadata-action
# See https://github.com/docker/build-push-action?tab=readme-ov-file#path-context
# See https://github.com/marketplace/actions/maximize-build-disk-space
name: Build image ${{ PREFIX }}

on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'main'
#   pull_request:
#     branches:
#       - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Move Docker directory
        run: |
          echo "Moving /var/lib/docker to $GITHUB_WORKSPACE"
          sudo systemctl stop docker
          sudo mv /var/lib/docker $GITHUB_WORKSPACE/docker_storage
          sudo ln -s $GITHUB_WORKSPACE/docker_storage /var/lib/docker
          sudo systemctl start docker
          sudo docker info
      -
        name: Check free space
        run: |
          echo "Free space:"
          df -h
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: List workspace
        run: |
          ls -l $GITHUB_WORKSPACE/
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/${{ PREFIX }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rangenet:${{ PREFIX }}